import React from 'react';
import { WeightCutResponse } from '../../types';
import './WeightCutResult.css';

interface WeightCutResultProps {
  result: WeightCutResponse;
}

const WeightCutResult: React.FC<WeightCutResultProps> = ({ result }) => {
  return (
    <div className="result">
      {result.warning_message && (
        <div className="warning">
          <h3>⚠️ Safety Warning</h3>
          <p>{result.warning_message}</p>
        </div>
      )}
      
      <div className="plan">
        <h3>📋 Your Weight Cut Plan</h3>
        <div className="plan-content">
          <pre>{result.plan}</pre>
        </div>
      </div>

      <div className="disclaimer">
        <p><strong>⚠️ IMPORTANT DISCLAIMER:</strong></p>
        <p>
          This plan is generated by AI and should be reviewed by a qualified 
          sports nutritionist or medical professional. Always prioritize your 
          health and safety over making weight.
        </p>
      </div>
    </div>
  );
};

export default WeightCutResult;
